version: '3.3'
services:
  mongodb_container:
    container_name: PICIPO-Backend
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: kononov
      MONGO_INITDB_ROOT_PASSWORD: 291091
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: